version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    networks:
      - network
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
    - 6379:6379
    networks:
      - network
    environment:
      - "TZ=America/Sao_Paulo"

volumes:
  db_data:

networks:
  network:
    driver: bridge